@tripId = f8ae9aea-c98c-4660-9214-310dda681071
@participantId = 342384fa-4126-4e1d-9e2f-8a615d624c70

### Create Trip
POST http://localhost:8080/trips
Content-Type: application/json

{
  "destination": "Paris",
  "starts_at": "2025-07-01T17:30:00Z",
  "ends_at": "2025-07-21T17:30:00Z",
  "emails_to_invite": [
    "email@email.com",
    "teste@email.com"
  ],
  "owner_name": "owner",
  "owner_email": "owner@email.com"
}

### Get Trip by ID
GET http://localhost:8080/trips/{{tripId}}

### Update Trip
PUT http://localhost:8080/trips/{{tripId}}
Content-Type: application/json

{
  "destination": "Lyon",
  "starts_at": "2025-07-01T17:30:00Z",
  "ends_at": "2025-07-21T17:30:00Z"
}

### Confirm Trip
GET http://localhost:8080/trips/{{tripId}}/confirm

### Invite Participant
POST http://localhost:8080/trips/{{tripId}}/invites
Content-Type: application/json

{
  "email": "invited@email.com"
}

### Confirm Participant
PATCH http://localhost:8080/participants/{{participantId}}/confirm

### Get Trip Participants
GET http://localhost:8080/trips/{{tripId}}/participants

### Create Trip Activity
POST http://localhost:8080/trips/{{tripId}}/activities
Content-Type: application/json

{
  "occurs_at": "2025-07-01T17:30:00Z",
  "title": "Atividade Teste"
}

### Get Trip Activities
GET http://localhost:8080/trips/{{tripId}}/activities

### Create Trip Link
POST http://localhost:8080/trips/{{tripId}}/links
Content-Type: application/json

{
  "title": "Google",
  "url": "https://google.com"
}

### Get Trip Links
GET http://localhost:8080/trips/{{tripId}}/links